apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  claimRef:
    namespace: default
    name: pvc-nfs
  nfs:
    server: 172.22.111.206
    path: "/srv/nfs/laramysql/"
  persistentVolumeReclaimPolicy: Retain
