apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
      tier: backend
  template:
    metadata:
      labels:
        app: php
        tier: backend
    spec:
      volumes:
      - name: depl-nfs
        persistentVolumeClaim:
          claimName: pvc-nfs
      containers:
      - name: php
        image: abdulbadi1524/php:7.4-fpm-alpine-plus
        resources:
          limits:
            cpu: "100m"
            memory: "100Mi"
        volumeMounts:
        - name: depl-nfs
          mountPath: /code
        securityContext:
            capabilities:
              add: ["SYS_ADMIN"]
        workingDir: /code/app
        lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "ln -sf /code/conf/php.ini /usr/local/etc/php/php.ini"]
---

apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
    tier: backend
spec:
  selector:
    app: php
    tier: backend
  ports:
    - protocol: TCP
      port: 9000