apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  #namespace: larapgsql
  labels:
    app: mysql
data:
  MYSQL_DATABASE: homestead
  MYSQL_USER: homestead
  MYSQL_PASSWORD: secret
  MYSQL_ROOT_PASSWORD: secret

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 500Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  #namespace: larapgsql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        imagePullPolicy: "IfNotPresent"
        resources:
          requests:
            cpu: "50m"
            memory: "512Mi"
          limits:
            cpu: 100m
            memory: 1024Mi
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_ROOT_PASSWORD
        volumeMounts:
        - mountPath: /var/lib/mysql/
          name: mysql-nfs
        securityContext:
            capabilities:
              add: ["SYS_ADMIN"]
        ports:
          - containerPort: 3306
            name: mysql
      volumes:
      - name: mysql-nfs
        persistentVolumeClaim:
          claimName: mysql-pv-claim

---

    apiVersion: v1
    kind: Service
    metadata:
      name: mysql
      #namespace: larapgsql
      labels:
        app: mysql
    spec:
      type: NodePort  
      selector:
        app: mysql
      ports:
      - name: mysql
        port: 3306
        nodePort: 30306