apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
    app: mysql
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  claimRef:
    namespace: default
    name: mysql-pv-claim
  nfs:
    server: 172.22.111.206
    path: "/srv/nfs/db_mysql/"
  persistentVolumeReclaimPolicy: Retain