apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  #namespace: larapgsql
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin:5.1.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
        env:
        - name: PMA_HOST
          value: mysql
        - name: PMA_PORT
          value: "3306"
        - name: MYSQL_ROOT_PASSWORD
          value: secret
        - name: UPLOAD_LIMIT
          value: 64M
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  #namespace: larapgsql
  labels:
    app: phpmyadmin
spec:
  type: NodePort
  selector:
    app: phpmyadmin
  ports:
  - port: 8088
    targetPort: 80
    nodePort: 30220